# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd82466c6d90d16eadf1dcb339e05079a1283bf222cea103f5bcdef6bfb19e7f44b62d05ed10b5e8dcddff6367804c974461ad46e44c6587310709181a22446

test:
  secret_key_base: 9f2dcde82b457f0a778d38d25248ee74d12f7b3fea679f4c882ee579cacb94fde612e2ecc6140d67250e55812f899126473951098d20cb8123fa4b0057ed68ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
